/**
 * Como o médico chama as coisas → as palavras que estão no texto. A chave é
 * o que se digita (sem acento, pode ter até 3 palavras); cada valor é uma
 * alternativa ("infarto" vale por "coronariana"). Uma alternativa com duas
 * palavras exige as duas.
 *
 * Vale para as duas abas do guia: o que não existe numa delas simplesmente
 * não casa lá.
 */
export const SYNONYM_TABLE: Readonly<Record<string, readonly string[]>> = {
  // Coração e vasos
  iam: ["coronariana", "infarto"],
  infarto: ["coronariana"],
  "ataque cardiaco": ["coronariana"],
  sca: ["coronariana"],
  "dor toracica": ["coronariana", "toracica"],
  "dor no peito": ["coronariana", "toracica"],
  angina: ["coronariana"],
  has: ["hipertensiva", "hipertensao"],
  "pressao alta": ["hipertensiva", "hipertensao"],
  "crise hipertensiva": ["hipertensiva"],
  hipertensao: ["hipertensiva"],
  "pressao baixa": ["choque", "noradrenalina"],
  hipotensao: ["choque", "noradrenalina"],
  ic: ["icad", "insuficiencia cardiaca"],
  icc: ["icad"],
  "insuficiencia cardiaca": ["icad"],
  eap: ["edema pulmao"],
  "edema de pulmao": ["eap"],
  fa: ["fibrilacao"],
  flutter: ["fibrilacao"],
  tsv: ["supraventricular"],
  tv: ["ventricular"],
  bradicardia: ["bradiarritmias"],
  bav: ["bradiarritmias", "bloqueio"],
  bavt: ["bradiarritmias"],
  marcapasso: ["bradiarritmias"],
  pcr: ["adrenalina", "bradiarritmias"],
  "parada cardiaca": ["adrenalina", "bradiarritmias"],
  tvp: ["trombose"],
  trombose: ["tvp"],
  tep: ["tromboembolismo"],
  embolia: ["tromboembolismo"],
  anticoagulacao: ["enoxaparina", "rivaroxabana", "heparina"],
  anticoagulante: ["enoxaparina", "rivaroxabana", "heparina"],
  aorta: ["disseccao"],
  // Neurologia
  avc: ["trombolise", "avc"],
  derrame: ["avc", "trombolise"],
  convulsao: ["convulsiva"],
  epilepsia: ["convulsiva"],
  "mal epileptico": ["convulsiva"],
  "crise epileptica": ["convulsiva"],
  "dor de cabeca": ["cefaleia", "enxaqueca"],
  cefaleia: ["enxaqueca"],
  migranea: ["enxaqueca"],
  labirintite: ["vertigem"],
  tontura: ["vertigem"],
  "paralisia facial": ["bell"],
  // Respiratório
  asma: ["asmatica"],
  bronquite: ["asmatica", "dpoc"],
  chiado: ["asmatica", "broncoespasmo"],
  broncoespasmo: ["asmatica"],
  enfisema: ["dpoc"],
  pac: ["pneumonia"],
  tb: ["tuberculose"],
  "falta de ar": ["dispneia"],
  "sangramento nasal": ["epistaxe"],
  "sangue no nariz": ["epistaxe"],
  garganta: ["faringoamigdalite", "faringite"],
  amigdalite: ["faringoamigdalite"],
  ouvido: ["otite"],
  sinusite: ["rinossinusite"],
  // Digestivo
  nausea: ["nauseas", "vomitos"],
  vomito: ["vomitos", "nauseas"],
  enjoo: ["nauseas", "vomitos", "cinetose"],
  "dor de barriga": ["diarreia", "colica"],
  gastroenterite: ["diarreia"],
  hemorroida: ["hemorroidaria"],
  hda: ["digestiva alta"],
  hdb: ["digestiva baixa"],
  "sangramento digestivo": ["hemorragia digestiva"],
  melena: ["hemorragia digestiva"],
  hematemese: ["digestiva alta"],
  "pedra na vesicula": ["colelitiase"],
  "colica biliar": ["colelitiase"],
  "pedra no rim": ["ureterolitiase", "nefretica", "colica renal"],
  "calculo renal": ["ureterolitiase", "nefretica", "colica renal"],
  "colica renal": ["ureterolitiase", "nefretica"],
  refluxo: ["gastroesofagico", "refluxo"],
  drge: ["gastroesofagico", "refluxo"],
  gastrite: ["dispepsia", "ulcerosa"],
  ulcera: ["ulcerosa"],
  pylori: ["pylori"],
  // Urinário, sexual, gestação
  itu: ["urinario", "cistite"],
  "infeccao urinaria": ["urinario", "cistite"],
  pielonefrite: ["pielonefrite", "urinario"],
  ist: ["uretrite", "sifilis", "tricomoniase", "herpes genital"],
  dst: ["uretrite", "sifilis", "tricomoniase", "herpes genital"],
  gonorreia: ["gonococica", "uretrite"],
  clamidia: ["uretrite"],
  corrimento: ["candidiase", "vaginose", "tricomoniase"],
  gravida: ["gestantes", "gestacao"],
  gravidez: ["gestantes", "gestacao"],
  gestante: ["gestantes"],
  crianca: ["pediatrica", "pediatria"],
  criancas: ["pediatrica", "pediatria"],
  infantil: ["pediatrica", "pediatria"],
  pediatria: ["pediatrica"],
  bebe: ["pediatrica", "neonatos", "lactentes"],
  "recem nascido": ["neonatos", "neonatal"],
  menstruacao: ["menstrual", "uterino"],
  // Metabólico
  cad: ["cetoacidose"],
  "acucar alto": ["cetoacidose", "glicemico", "hiperglicemia"],
  hiperglicemia: ["cetoacidose", "glicemico"],
  "acucar baixo": ["hipoglicemia"],
  diabetes: ["glicemico", "insulina", "diabetes"],
  dm: ["glicemico", "insulina", "diabetes"],
  "potassio alto": ["hipercalemia"],
  "k alto": ["hipercalemia"],
  hiperpotassemia: ["hipercalemia"],
  "potassio baixo": ["hipocalemia"],
  "k baixo": ["hipocalemia"],
  hipopotassemia: ["hipocalemia"],
  "sodio baixo": ["hiponatremia"],
  "sodio alto": ["hipernatremia"],
  "calcio baixo": ["hipocalcemia"],
  "calcio alto": ["hipercalcemia"],
  magnesio: ["hipomagnesemia", "hipermagnesemia"],
  // Infecção, alergia, intoxicação
  "infeccao generalizada": ["sepse"],
  "choque septico": ["sepse"],
  alergia: ["alergicas", "anafilatico", "urticaria"],
  anafilaxia: ["anafilatico"],
  "choque anafilatico": ["anafilatico"],
  coceira: ["urticaria", "escabiose", "dermatite"],
  cobra: ["ofidico"],
  "picada de cobra": ["ofidico"],
  jararaca: ["ofidico", "botropico"],
  cascavel: ["ofidico", "crotalico"],
  coral: ["ofidico", "elapidico"],
  surucucu: ["ofidico", "laquetico"],
  escorpiao: ["escorpionismo"],
  aranha: ["araneismo"],
  mordida: ["mordeduras", "mordedura"],
  cachorro: ["mordeduras"],
  gato: ["mordeduras"],
  envenenamento: ["intoxicacao", "descontaminacao"],
  overdose: ["intoxicacao", "naloxona"],
  chumbinho: ["organofosforados"],
  agrotoxico: ["organofosforados"],
  bebado: ["alcoolica"],
  alcool: ["alcoolica"],
  embriaguez: ["alcoolica"],
  abstinencia: ["abstinencia"],
  "delirium tremens": ["abstinencia"],
  // Procedimentos, UTI
  iot: ["intubacao"],
  intubar: ["intubacao"],
  intubacao: ["intubacao"],
  sri: ["intubacao"],
  "sequencia rapida": ["intubacao"],
  sedacao: ["sedoanalgesia", "intubacao", "sedacao"],
  dva: ["vasoativas"],
  "droga vasoativa": ["vasoativas"],
  vasopressor: ["vasoativas", "noradrenalina"],
  paliativo: ["paliativos"],
  transfusao: ["hemacias", "plaquetas", "hemocomponentes"],
  sangue: ["hemacias", "transfusao"],
  agitacao: ["agitacao", "agressividade"],
  agitado: ["agitacao", "agressividade"],
  surto: ["psicotica", "agitacao"],
  psicose: ["psicotica"],
  panico: ["panico", "ansiedade"],
  // Nomes comerciais e apelidos → princípio ativo
  nora: ["noradrenalina"],
  epinefrina: ["adrenalina"],
  norepinefrina: ["noradrenalina"],
  dobuta: ["dobutamina"],
  novalgina: ["dipirona"],
  tylenol: ["paracetamol"],
  buscopan: ["escopolamina"],
  plasil: ["metoclopramida"],
  rivotril: ["clonazepam"],
  haldol: ["haloperidol"],
  dormonid: ["midazolam"],
  valium: ["diazepam"],
  gardenal: ["fenobarbital"],
  cataflan: ["diclofenaco"],
  voltaren: ["diclofenaco"],
  tramal: ["tramadol"],
  decadron: ["dexametasona"],
  "solu medrol": ["metilprednisolona"],
  zofran: ["ondansetrona"],
  lasix: ["furosemida"],
  aldactone: ["espironolactona"],
  marevan: ["varfarina"],
  xarelto: ["rivaroxabana"],
  eliquis: ["apixabana"],
  pradaxa: ["dabigatrana"],
  aspirina: ["aas"],
  keflex: ["cefalexina"],
  zitromax: ["azitromicina"],
  amoxil: ["amoxicilina"],
  fenergan: ["prometazina"],
  polaramine: ["dexclorfeniramina"],
  hidantal: ["fenitoina"],
  sumax: ["sumatriptano", "sumatriptana"],
  // Receitas prontas (consultório)
  gripe: ["resfriado", "gripal"],
  resfriado: ["gripe"],
  "dor nas costas": ["lombalgia"],
  lombar: ["lombalgia"],
  cobreiro: ["zoster"],
  frieira: ["tinha", "micose"],
  micose: ["tinha", "micose", "onicomicose"],
  unha: ["onicomicose"],
  verme: ["verminose", "oxiuriase", "albendazol"],
  vermes: ["verminose", "oxiuriase", "albendazol"],
  lombriga: ["verminose", "albendazol"],
  sarna: ["escabiose"],
  piolho: ["pediculose"],
  tireoide: ["hipotireoidismo", "levotiroxina"],
  colesterol: ["colesterol", "atorvastatina"],
  prostata: ["prostata", "hpb"],
  "enjoo de viagem": ["cinetose"],
  pressao: ["hipertensao", "hipertensiva"],
};
