-- Renova — 2026-09-06
-- Run via Supabase SQL editor. The app role has no DDL privilege.
-- Every statement is idempotent; running it twice is harmless.
--
-- 1. booking_attempts: per-IP rate limiting for the public portal (Pendings §8).
-- 2. professionals.memed_specialty_id: Memed wants a specialty *id* (Pendings §19c).
-- 3. RLS on memed_prescriptions: the 2026-08-18 migration created the table
--    without it. Every other table has RLS with a renova_app-only policy so the
--    auto-generated REST API returns nothing; this brings the new table in line.

-- ---------- 1. booking attempts ----------
CREATE TABLE IF NOT EXISTS booking_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_booking_attempts_ip_time ON booking_attempts (ip, created_at);

GRANT SELECT, INSERT, DELETE ON booking_attempts TO renova_app;
GRANT USAGE, SELECT ON SEQUENCE booking_attempts_id_seq TO renova_app;

ALTER TABLE booking_attempts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON booking_attempts;
CREATE POLICY renova_app_all ON booking_attempts FOR ALL TO renova_app USING (true) WITH CHECK (true);
REVOKE ALL ON booking_attempts FROM anon, authenticated;

-- ---------- 2. Memed specialty id ----------
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS memed_specialty_id text;

-- ---------- 3. RLS on memed_prescriptions ----------
ALTER TABLE memed_prescriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON memed_prescriptions;
CREATE POLICY renova_app_all ON memed_prescriptions FOR ALL TO renova_app USING (true) WITH CHECK (true);
REVOKE ALL ON memed_prescriptions FROM anon, authenticated;
REVOKE ALL ON SEQUENCE memed_prescriptions_id_seq FROM anon, authenticated;
