-- Renova — 2026-09-09
-- Run via Supabase SQL editor. The app role has no DDL privilege.
-- Every statement is idempotent; running it twice is harmless.
--
-- documents: the clinic's own documents (atestado, encaminhamento, laudo,
-- orientações) issued from the prontuário, each with a public validation
-- code (QR on the sheet -> /validar/<code>). The prescription stays with Memed.
-- document_templates: "Modelos" per professional (or clinic-wide when
-- professional_id is NULL) with {{placeholders}}.
-- patients.allergies / medications: structured fields shown in the prontuário
-- and sent to Memed as clinical history.
-- encounters.return_*: "retorno em N dias" recall.
-- hub_submissions.kind gains 'renovacao' (patient asks to renew a prescription).

CREATE TABLE IF NOT EXISTS documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id bigint NOT NULL REFERENCES patients(id),
  professional_id bigint NOT NULL REFERENCES professionals(id),
  encounter_id bigint REFERENCES encounters(id),
  kind text NOT NULL CHECK (kind IN ('atestado','encaminhamento','laudo','orientacoes')),
  subkind text,
  title text NOT NULL,
  body text NOT NULL,
  fields text,
  code text NOT NULL UNIQUE,
  issued_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD'),
  shared_with_patient integer NOT NULL DEFAULT 1,
  revoked_at text,
  revoke_reason text,
  created_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_documents_patient ON documents (patient_id, created_at);
CREATE INDEX IF NOT EXISTS idx_documents_encounter ON documents (encounter_id);

GRANT SELECT, INSERT, UPDATE ON documents TO renova_app;
GRANT USAGE, SELECT ON SEQUENCE documents_id_seq TO renova_app;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON documents;
CREATE POLICY renova_app_all ON documents FOR ALL TO renova_app USING (true) WITH CHECK (true);
REVOKE ALL ON documents FROM anon, authenticated;
REVOKE ALL ON SEQUENCE documents_id_seq FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS document_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  professional_id bigint REFERENCES professionals(id),
  kind text NOT NULL CHECK (kind IN ('atestado','encaminhamento','laudo','orientacoes')),
  subkind text,
  name text NOT NULL,
  title text,
  body text NOT NULL,
  fields text,
  created_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_document_templates_prof ON document_templates (professional_id, kind);

GRANT SELECT, INSERT, UPDATE, DELETE ON document_templates TO renova_app;
GRANT USAGE, SELECT ON SEQUENCE document_templates_id_seq TO renova_app;
ALTER TABLE document_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON document_templates;
CREATE POLICY renova_app_all ON document_templates FOR ALL TO renova_app USING (true) WITH CHECK (true);
REVOKE ALL ON document_templates FROM anon, authenticated;
REVOKE ALL ON SEQUENCE document_templates_id_seq FROM anon, authenticated;

ALTER TABLE patients ADD COLUMN IF NOT EXISTS allergies text;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS medications text;

ALTER TABLE encounters ADD COLUMN IF NOT EXISTS return_days integer;
ALTER TABLE encounters ADD COLUMN IF NOT EXISTS return_due text;
ALTER TABLE encounters ADD COLUMN IF NOT EXISTS return_reminded_at text;
CREATE INDEX IF NOT EXISTS idx_encounters_return_due ON encounters (return_due);

ALTER TABLE hub_submissions DROP CONSTRAINT IF EXISTS hub_submissions_kind_check;
ALTER TABLE hub_submissions ADD CONSTRAINT hub_submissions_kind_check
  CHECK (kind IN ('remarcacao','avaliacao','pre_consulta','renovacao'));
