-- Renova — 2026-10-01 — memória de respostas da Super Inteligência (guia de plantão)
-- Run via Supabase SQL editor. The app role has no DDL privilege.
-- Every statement is idempotent; running it twice is harmless.
--
-- A mesma pergunta ao guia, feita de novo por qualquer médico, volta na hora
-- e sem custo de IA. `question_key` é o conjunto de palavras clínicas da
-- pergunta (radicais, sem ordem) + os números (src/lib/guide-answer-cache.ts);
-- `guide_version` muda quando o texto do guia muda, o que invalida tudo.
-- Não guarda quem perguntou nem dado de paciente.
--
-- Sem esta tabela o app funciona igual: a memória fica só na instância.

CREATE TABLE IF NOT EXISTS guide_answer_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_key text NOT NULL,
  guide_version text NOT NULL,
  -- A primeira forma em que a pergunta foi feita (só para conferência).
  question text NOT NULL,
  answer text NOT NULL,
  -- JSON: [{ "id", "slug", "topic", "section" }]
  sources text NOT NULL,
  hits integer NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  last_used_at text,
  UNIQUE (question_key, guide_version)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON guide_answer_cache TO renova_app;
GRANT USAGE, SELECT ON SEQUENCE guide_answer_cache_id_seq TO renova_app;
ALTER TABLE guide_answer_cache ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON guide_answer_cache;
CREATE POLICY renova_app_all ON guide_answer_cache FOR ALL TO renova_app USING (true) WITH CHECK (true);
