-- Renova — 2026-09-28 — rascunhos do compositor de documentos
-- Run via Supabase SQL editor. The app role has no DDL privilege.
-- Every statement is idempotent; running it twice is harmless.
--
-- O compositor ("Emitir documentos") abre como pop-up. Fechar sem emitir
-- guarda o que estava montado — pilha, receituário e o editor — como
-- rascunho do paciente, para continuar depois em qualquer computador.
-- Emitir a partir de um rascunho apaga o rascunho.
--
-- `state` é o JSON do compositor (src/lib/drafts.ts); `title` é o resumo
-- mostrado na lista ("Receituário · 3 medicamentos + Atestado").

CREATE TABLE IF NOT EXISTS document_drafts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id bigint NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  -- Quem montou (o profissional da sessão; null para o admin sem cadastro de profissional).
  professional_id bigint REFERENCES professionals(id),
  user_id bigint REFERENCES users(id),
  title text NOT NULL,
  state text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_document_drafts_patient ON document_drafts (patient_id, updated_at);

GRANT SELECT, INSERT, UPDATE, DELETE ON document_drafts TO renova_app;
GRANT USAGE, SELECT ON SEQUENCE document_drafts_id_seq TO renova_app;
ALTER TABLE document_drafts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON document_drafts;
CREATE POLICY renova_app_all ON document_drafts FOR ALL TO renova_app USING (true) WITH CHECK (true);
