-- Renova — 2026-09-06
-- Run via Supabase SQL editor. The app role has no DDL privilege.
-- Every statement is idempotent; running it twice is harmless.
--
-- attachments: "Anexos no prontuário" — exam results, photos and PDFs uploaded
-- onto a patient, optionally tied to an encounter. Files are stored as bytea in
-- Postgres on purpose: the clinic is small and this avoids a second vendor and
-- credential set. The app enforces a 10 MB cap per file and only accepts
-- PDF/JPEG/PNG/WebP. Listing queries must never select `data`.

CREATE TABLE IF NOT EXISTS attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id bigint NOT NULL REFERENCES patients(id),
  encounter_id bigint REFERENCES encounters(id),
  file_name text NOT NULL,
  mime_type text NOT NULL,
  size_bytes integer NOT NULL,
  data bytea NOT NULL,
  created_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_attachments_patient ON attachments (patient_id);

GRANT SELECT, INSERT, DELETE ON attachments TO renova_app;
GRANT USAGE, SELECT ON SEQUENCE attachments_id_seq TO renova_app;

ALTER TABLE attachments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON attachments;
CREATE POLICY renova_app_all ON attachments FOR ALL TO renova_app USING (true) WITH CHECK (true);
REVOKE ALL ON attachments FROM anon, authenticated;
REVOKE ALL ON SEQUENCE attachments_id_seq FROM anon, authenticated;
