-- Renova — 2026-09-07
-- Run via Supabase SQL editor. The app role has no DDL privilege.
-- Every statement is idempotent; running it twice is harmless.
--
-- hub_submissions: what the patient sends from the portal (/p/[token]) —
-- a reschedule request, a post-visit rating, the pre-consult questionnaire.
-- One table, discriminated by `kind`, so the clinic has a single inbox.
--   remarcacao   → message ("quando fica bom"), handled_at when reception dealt with it
--   avaliacao    → rating 1..5, optional message, publish=1 if the patient allowed
--                  the comment (first name only) on the public landing page
--   pre_consulta → answers (JSON text: motivo, sintomas, medicamentos, alergias)
--
-- push_subscriptions: Web Push endpoints the patient opted into from the
-- installed portal. The daily cron sends the "véspera" reminder through them.

CREATE TABLE IF NOT EXISTS hub_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id bigint NOT NULL REFERENCES patients(id),
  appointment_id bigint REFERENCES appointments(id),
  kind text NOT NULL CHECK (kind IN ('remarcacao','avaliacao','pre_consulta')),
  rating integer CHECK (rating BETWEEN 1 AND 5),
  message text,
  answers text,
  publish integer NOT NULL DEFAULT 0,
  handled_at text,
  created_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_hub_submissions_patient ON hub_submissions (patient_id);
CREATE INDEX IF NOT EXISTS idx_hub_submissions_kind ON hub_submissions (kind, created_at);
CREATE INDEX IF NOT EXISTS idx_hub_submissions_appt ON hub_submissions (appointment_id);

GRANT SELECT, INSERT, UPDATE ON hub_submissions TO renova_app;
GRANT USAGE, SELECT ON SEQUENCE hub_submissions_id_seq TO renova_app;

ALTER TABLE hub_submissions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON hub_submissions;
CREATE POLICY renova_app_all ON hub_submissions FOR ALL TO renova_app USING (true) WITH CHECK (true);
REVOKE ALL ON hub_submissions FROM anon, authenticated;
REVOKE ALL ON SEQUENCE hub_submissions_id_seq FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id bigint NOT NULL REFERENCES patients(id),
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  disabled integer NOT NULL DEFAULT 0,
  last_success_at text,
  last_error text,
  created_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_patient ON push_subscriptions (patient_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON push_subscriptions TO renova_app;
GRANT USAGE, SELECT ON SEQUENCE push_subscriptions_id_seq TO renova_app;

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON push_subscriptions;
CREATE POLICY renova_app_all ON push_subscriptions FOR ALL TO renova_app USING (true) WITH CHECK (true);
REVOKE ALL ON push_subscriptions FROM anon, authenticated;
REVOKE ALL ON SEQUENCE push_subscriptions_id_seq FROM anon, authenticated;

-- The automatic reminder for this appointment already went out (push).
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS reminder_sent_at text;
