-- Receituário próprio: catálogo de medicamentos + o tipo de documento.
--
-- O catálogo vem da Lista de Preços da CMED/ANVISA (dados abertos, ~25 mil
-- apresentações, atualizada todo mês). O campo que importa não é o preço: é a
-- **tarja**, que decide em que receituário cada medicamento pode sair
-- (simples, controle especial em duas vias, ou Notificação de Receita).
--
-- Importação: `node data/import-medications.mjs` (baixa o CSV e recarrega a
-- tabela inteira). Rodar de novo troca o conteúdo sem derrubar o índice.
--
-- Idempotente.

CREATE TABLE IF NOT EXISTS medications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  substance text NOT NULL,
  product text NOT NULL DEFAULT '',
  presentation text NOT NULL DEFAULT '',
  concentration text,
  laboratory text,
  therapeutic_class text,
  -- Já normalizada na importação: livre | vermelha | vermelha_retida | preta | desconhecida
  tarja text NOT NULL DEFAULT 'desconhecida',
  registration text,
  -- Preço máximo ao consumidor (PMC 18%, em centavos) — referência para o paciente.
  max_price_cents integer,
  -- 1 quando a CMED marca o produto como comercializado.
  marketed integer NOT NULL DEFAULT 1,
  -- Texto sem acento e em minúsculas, para o autocompletar.
  substance_search text NOT NULL DEFAULT '',
  product_search text NOT NULL DEFAULT ''
);

-- Busca por prefixo ("dipi" → DIPIRONA): `text_pattern_ops` faz o LIKE 'x%'
-- usar o índice. Sem isto, cada tecla varre 25 mil linhas.
CREATE INDEX IF NOT EXISTS idx_medications_substance ON medications (substance_search text_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_medications_product ON medications (product_search text_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_medications_marketed ON medications (marketed);

ALTER TABLE medications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS renova_app_all ON medications;
CREATE POLICY renova_app_all ON medications FOR ALL TO renova_app USING (true) WITH CHECK (true);
REVOKE ALL ON medications FROM anon, authenticated;

-- O receituário entra como mais um tipo de documento: herda código de
-- autenticidade, /validar, portal do paciente, renovação e a lista do
-- prontuário, sem nada novo.
ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_kind_check;
ALTER TABLE documents ADD CONSTRAINT documents_kind_check
  CHECK (kind IN ('atestado','encaminhamento','laudo','orientacoes','receituario'));

ALTER TABLE document_templates DROP CONSTRAINT IF EXISTS document_templates_kind_check;
ALTER TABLE document_templates ADD CONSTRAINT document_templates_kind_check
  CHECK (kind IN ('atestado','encaminhamento','laudo','orientacoes','protocolo','receituario'));
