-- Memed digital prescription — Phase 0 schema.
-- Run via Supabase SQL editor. The app role has no DDL privilege.

ALTER TABLE professionals ADD COLUMN IF NOT EXISTS cpf text;
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS board_code text;
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS board_number text;
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS board_state text;
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS birth_date text;
ALTER TABLE professionals ADD COLUMN IF NOT EXISTS memed_external_id text;

CREATE TABLE IF NOT EXISTS memed_prescriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encounter_id bigint REFERENCES encounters(id),
  patient_id bigint NOT NULL REFERENCES patients(id),
  professional_id bigint NOT NULL REFERENCES professionals(id),
  memed_prescription_id text NOT NULL UNIQUE,
  patient_link text,
  pdf_url text,
  status text NOT NULL DEFAULT 'emitida' CHECK (status IN ('emitida','excluida')),
  created_at text NOT NULL DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_memed_presc_patient ON memed_prescriptions(patient_id);
CREATE INDEX IF NOT EXISTS idx_memed_presc_encounter ON memed_prescriptions(encounter_id);

GRANT SELECT, INSERT, UPDATE ON memed_prescriptions TO renova_app;
GRANT USAGE, SELECT ON SEQUENCE memed_prescriptions_id_seq TO renova_app;
